# vim: filetype=yaml.ansible

# General

packages_bash_comp_dir: /etc/bash_completion.d
packages_zsh_comp_dir: /usr/local/share/zsh/site-functions
packages_man_dir: /usr/local/share/man/man1

# Packages

packages_fd_name: fd
packages_python_name: python3
packages_pip_name: python3-pip
packages_venv_name: python3-venv
