# vim: filetype=yaml.ansible

# General

bash_completions_dir: /etc/bash_completion.d
zsh_completions_dir: /usr/local/share/zsh/site-functions
man_dir: /usr/local/share/man/man1

# Packages

fd_pkg_name: fd
