#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed marksman; then
    if [ "${__OS_ID}" = "mac" ]; then
      uninstall_pkg marksman
    else
      remove_system_bins "marksman"
    fi
  fi
else
  if [ "${__OS_ID}" = "mac" ]; then
    is_installed marksman || install_pkg marksman
  else
    # Marksman versions and tags are mismatched formats, just install only if it is not installed
    if is_installed marksman; then
      return
    fi
    #shellcheck disable=SC2317
    function __marksmanls_install_fn() {
      for f in marksman*; do
        _run mv "${f}" marksman
        break
      done
      _run chmod +x marksman
      install_system_bins '.' './marksman'
    }
    # shellcheck disable=SC2317
    function __marksman_filter_fn() { return 0; }
    install_gh_pkg 'artempyanykh/marksman' 'latest' 'marksman --version' '__marksmanls_install_fn' \
      -x \
      -f '__marksman_filter_fn'
    unset -f __marksmanls_install_fn __marksman_filter_fn
  fi
fi
