#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${__IS_WSL}" -ne 1 ]; then
  return
fi

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed win32yank; then
    remove_system_bins "win32yank"
  fi
else
  # shellcheck disable=SC2317
  function __win32yank_install_fn() {
    chmod +x ./win32yank.exe
    install_system_bins '.' './win32yank.exe'
  }
  # shellcheck disable=SC2317
  function __win32yank_filter_fn() {
    if ! echo "${1}" | grep '\.zip$'; then
      debug "Asset '${1}' failed filter" && return 1
    fi
  }
  # shellcheck disable=SC2317
  function __win32yank_system_filter_fn() {
    return 0
  }
  # shellcheck disable=SC2317
  function __win32yank_arch_filter_fn() {
    echo "${1}" | grep -q "x64"
  }
  if ! is_installed win32yank; then
    install_gh_pkg 'equalsraf/win32yank' 'latest' 'echo ""' '__win32yank_install_fn' \
      -f '__win32yank_filter_fn' \
      -s '__win32yank_system_filter_fn' \
      -a '__win32yank_arch_filter_fn'
  fi
  unset -f __win32yank_install_fn __win32yank_filter_fn __win32yank_system_filter_fn __win32yank_arch_filter_fn
fi
