# vim: filetype=conf

# General settings
# ================

# Bind Prefix to c-a (Press 'C-a' twice to send 'C-a')
unbind C-b
set -g prefix C-space
bind C-space send-prefix
# Mouse support
set-option -g mouse on
# Remove escape time delay
set -sg escape-time 0
# Start indices from 1 for both windows and panes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
# Scroll history
set -g history-limit 100000
# No bells at all
set-option -g bell-action none
# Set shell
set-option -g default-command /usr/bin/fish
set-option -g default-shell /usr/bin/fish

# Key bindings
# =============

# Key modes: emacs for status, vi for all other
set -g status-keys emacs
set -g mode-keys vi

# Reload tmux configuration
bind C-r source-file ~/.tmux.conf \; display "Config reloaded"

# split window and fix path for tmux 1.9
bind \ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind space last-window

# Move between panes with vi keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# Appearence
# ============

# Ensure colors look correct
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# Status bar
set -g status           on
set -g status-position  bottom
set -g status-interval  15
set -g monitor-activity off

# Format (run $XDG_CONFIG_HOME/base16-shell/colortest for color codes)
set-window-option -g status-bg colour00
set-window-option -g status-fg colour05
set-window-option -g status-left        ""
set-window-option -g status-left-length 50
set-window-option -g window-status-current-format "#[bg=colour18,fg=colour03] #W "
set-window-option -g window-status-format "#[fg=colour08,bold] #I#[default] #W "
set-window-option -g status-right "#[fg=colour03] #S "
set-window-option -g window-status-style fg=colour08,bg=colour00
set-window-option -g pane-active-border-style fg=colour03
set-window-option -g pane-border-style fg=colour08
set-window-option -g message-style fg=colour01,bg=colour00
