# vim: filetype=conf

# General settings
# ================

# Bind Prefix to c-space (Press 'C-space' twice to send 'C-space')
unbind C-b
set -g prefix C-space
bind C-space send-prefix
# Set default shell
set-option -g default-shell $SHELL
# Mouse support
set-option -g mouse on
# Remove escape time delay
set -sg escape-time 0
# Time in miliseconds between multiple commands to be considered as part
# of the same chain (with the '-r' flag)
set -g repeat-time 350
# Focus events enabled for terminals that support them
set -g focus-events on
# Ensure colors look correct
set-option -g default-terminal "screen-256color"
# NOTE auto rename is disabled for the given window upon manual rename.
set -g allow-rename off
# manpage says "on" is bad for shells…
set -g aggressive-resize off
# Start indices from 1 for both windows and panes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
# Scroll history
set -g history-limit 25000
# No bells at all
set-option -g bell-action none

# Key bindings
# =============

# Key modes: emacs for status, vi for all other
set -g status-keys emacs
set -g mode-keys vi

# Edit configuration and reload
bind C-e new-window -n 'tmux.conf' \
    "sh -c '\${EDITOR:-vim} ~/.tmux.conf && " \
    "tmux source ~/.tmux.conf && tmux display \"Config reloaded\"'"
# Reload tmux configuration
bind C-r source-file ~/.tmux.conf \; display "Config reloaded"

# Panes
bind x kill-pane
bind -r o select-pane -t :.+ # Goto next pane

# Windows
bind C-x confirm-before -p "kill other windows? (y/n)" "kill-window -a"
bind-key -n MouseDrag1Status swap-window -t= # Drag to re-order
bind-key -n DoubleClick1Status new-window # Double click for new window
bind -r p previous-window
bind -r n next-window

# Sessions
bind Q confirm-before -p "kill-session #S? (y/n)" kill-session

# Copy mode
bind v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Appearence and status bar
# =========================

# Status bar
set -g status           on
set -g status-position  bottom
set -g status-interval  15
set -g monitor-activity off

# Format (run $XDG_CONFIG_HOME/base16-shell/colortest for color codes)
set-window-option -g status-bg colour00
set-window-option -g status-fg colour05
set-window-option -g status-left        ""
set-window-option -g status-left-length 50
set-window-option -g window-status-current-format " #[bg=colour18,fg=colour03]#W "
set-window-option -g window-status-format " #[fg=colour08,bold]#I #[default]#W "
set-window-option -g status-right " #[fg=colour03]#S "
set-window-option -g window-status-style fg=colour08,bg=colour00
set-window-option -g pane-active-border-style fg=colour03
set-window-option -g pane-border-style fg=colour08
set-window-option -g message-style fg=colour01,bg=colour00

# Plugins
# ========

TPLUG_DIR='~/.cache/tmux/plugins'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'

# Startup
# ========

set-environment -g TMUX_PLUGIN_MANAGER_PATH $TPLUG_DIR
if "test ! -d $TPLUG_DIR/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $TPLUG_DIR/tpm && $TPLUG_DIR/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b $TPLUG_DIR/tpm/tpm
