#!/bin/bash
#
# Installs core dependencies needed to deploy dotfiles

# Usage: has <cmd-1> <cmd-2> ... <cmd-n>
function has {
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null || return 1
  done
}

# - Installs core dependencies:
#   - curl
#   - gnu-stow
#   - python3
#   - python3-pip
#   - ansible
function install_deps {
  echo "### Installing dependencies"
  # Exit if anything fails within the function
  set -e

  # Install required apps
  os="$(uname)"
  case $os in
    'Darwin')
      echo "### Detected macOS"
      brew update
      brew install curl stow python
      pipx ensurepath
      ;;
    'Linux')
      echo "### Detected Linux"
      if [ -f /etc/os-release ]; then
        # Install core dependencies
        if grep -q -E '(debian|ubuntu|linuxmint)' /etc/os-release; then
          echo "Detected Debian/Ubuntu/Linux Mint"
          sudo apt-get update
          sudo apt-get install -y curl stow python3 python3-pip
        elif grep -q -E '(centos|rhel|fedora)' /etc/os-release; then
          echo "Detected CentOS/RHEL/Fedora"
          if [ -f /etc/centos-release ]; then
            sudo yum update
            sudo yum install -y epel-release
          fi
          sudo yum install -y curl stow python3 python3-pip
        elif grep -q -E '(arch)' /etc/os-release; then
          echo "Detected Arch"
          sudo pacman -Syyu --noconfirm curl stow python python-pip
        elif grep -q -E '(opensuse)' /etc/os-release; then
          echo "Detected openSUSE"
          sudo zypper update
          sudo zypper install -y curl stow python3 python3-pip
        else
          echo "Unsupported Linux distribution"
          exit 1
        fi
      else
        echo "Unsupported Linux distribution"
        exit 1
      fi
      ;;
    *)
      echo "Unsupported OS"
      exit 1
      ;;
  esac

  # Install ansible and community modules
  python3 -m pip install --user ansible
  ansible-galaxy collection install community.general
}

#-
#  Main
#-

# Install deps if not installed
if ! has curl stow ansible; then
  if ! install_deps; then
    echo "### Failed to install dependencies"
    exit 0
  fi
fi

# Run Ansible
ansible-playbook -i ./hosts ./playbook.yml --ask-become-pass
