#!/bin/bash

# Detect architecture
architecture=""
case "$(uname -s)" in
  Linux)
    case "$(uname -m)" in
      x86_64) architecture="x86_64-linux" ;;
      aarch64) architecture="aarch64-linux" ;;
      i686) architecture="i686-linux" ;;
      *) echo "ERROR: Unsupported architecture" && exit 1 ;;
    esac
    ;;
  Darwin)
    case "$(uname -m)" in
      x86_64) architecture="x86_64-darwin" ;;
      arm64) architecture="aarch64-darwin" ;;
      *) echo "ERROR: Unsupported architecture" && exit 1 ;;
    esac
    ;;
  *)
    echo "ERROR: Unsupported operating system" && exit 1
    ;;
esac

echo "## System Info: $architecture"

# Run home-manager
if command -v home-manager >/dev/null; then
  home-manager switch \
    -b backup \
    --impure \
    --extra-experimental-features "nix-command flakes" \
    --flake ~/dotfiles#simifa-"${architecture}"
else
  nix --extra-experimental-features "nix-command flakes" run \
    home-manager/release-24.05 switch -- \
    -b backup \
    --impure \
    --extra-experimental-features "nix-command flakes" \
    --flake ~/dotfiles#simifa-"${architecture}"
fi
