# vim: filetype=yaml.ansible

- name: Set up local development environment
  hosts: local
  roles:
    - {role: git, tags: ['git', 'bootstrap']}
    - {role: system, tags: ['system', 'bootstrap']}
    - {role: node, tags: ['node', 'bootstrap']}
    - {role: python, tags: ['python', 'bootstrap']}
    - {role: sh, tags: ['sh', 'bootstrap']}
    - {role: atool, tags: ['atool']}
    - {role: bat, tags: ['bat']}
    - {role: bitwise, tags: ['bitwise']}
    - {role: btop, tags: ['btop']}
    - {role: calc, tags: ['calc']}
    - {role: cheat, tags: ['cheat']}
    - {role: delta, tags: ['delta']}
    - {role: editor-tools, tags: ['editor-tools']}
    - {role: elinks, tags: ['elinks']}
    - {role: eza, tags: ['eza']}
    - {role: fd, tags: ['fd']}
    - {role: fzf, tags: ['fzf']}
    - {role: github, tags: ['github']}
    - {role: lazygit, tags: ['lazygit']}
    - {role: misc-dots, tags: ['misc-dots']}
    - {role: neovim, tags: ['neovim']}
    - {role: ripgrep, tags: ['ripgrep']}
    - {role: rsync, tags: ['rsync']}
    - {role: tig, tags: ['tig']}
    - {role: tinty, tags: ['tinty']}
    - {role: tmux, tags: ['tmux']}
    - {role: trash, tags: ['trash']}
    - {role: unison, tags: ['unison']}
    - {role: wslopen, tags: ['wslopen']}
    - {role: wslu, tags: ['wslu']}
    - {role: zellij, tags: ['zellij']}
    - {role: zoxide, tags: ['zoxide']}
