#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed fzf; then
    if [ "${__OS_ID}" = "mac" ]; then
      uninstall_pkg fzf
    else
      remove_system_bins "fzf"
    fi
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if [ "${__OS_ID}" = "mac" ]; then
    is_installed fzf || install_pkg fzf
  else
    # shellcheck disable=SC2317
    function __fzf_install_fn() {
      install_system_bins '.' './fzf'
    }
    install_gh_pkg 'junegunn/fzf' 'latest' 'fzf --version' '__fzf_install_fn'
    unset -f __fzf_install_fn
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
