# Main
# ====

- name: Install core common gui packages
  become: true
  apt:
    name:
      - arandr
      - autorandr
      - dunst
      - mpv
      - nitrogen
      - pasystray
      - peek
      - policykit-1-gnome
      - ppa-purge
      - redshift
      - rofi
      - screenkey
      - scrot
      - zathura
    state: present
