# Main
# ====

- name: Install core common packages
  become: true
  package:
    name:
      - atool
      - bat
      - bitwise
      - calc
      - cloc
      - elinks
      - "{{ fd_pkg_name }}"
      - fzf
      - htop
      - jq
      - nodejs
      - npm
      - "{{ python_pkg_name }}"
      - "{{ pip_pkg_name }}"
      - ripgrep
      - rsync
      - tig
      - tmux
      - tree
      - unison
      - zsh
    state: present

- name: Install common pip packages
  become: true
  pip:
    name:
      - pynvim
      - trash-cli
    state: present

- name: Install common global npm packages
  become: true
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop:
    - neovim

- name: Create symbolic link to fd binary if fdfind is used
  become: true
  file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  when: "'/usr/bin/fdfind' is file and '/usr/local/bin/fd' is not file"
