#-
#  Checks
#-

- command_exists:
    command: delta
  register: delta_cmd
  ignore_errors: true

#-
#  Main
#-

- name: Install git-delta
  become: true
  block:
    - name: Get latest version of git-delta
      get_latest_github_tag:
        owner: dandavison
        repo: delta
      register: gh_tag
    - name: Extract delta archive
      unarchive:
        src: "https://github.com/dandavison/delta/releases/download/{{ gh_tag.latest }}/delta-{{ gh_tag.latest }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/usr/local/bin"
        remote_src: yes
        extra_opts:
          - "--strip-components=1"
          - "delta-{{ gh_tag.latest }}-x86_64-unknown-linux-gnu/delta"
  when: not delta_cmd.exists
