# vim: filetype=yaml.ansible

- name: Install git-delta
  become: true
  when: "not ('delta' | is_installed)"
  block:
    - name: Get latest version of git-delta
      get_latest_github_tag:
        owner: dandavison
        repo: delta
      register: gh_tag
    - name: Extract delta archive
      ansible.builtin.unarchive:
        src: "https://github.com/dandavison/delta/releases/download/{{ gh_tag.latest }}/delta-{{ gh_tag.latest }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        extra_opts:
          - "--strip-components=1"
          - "delta-{{ gh_tag.latest }}-x86_64-unknown-linux-gnu/delta"
