# vim: filetype=yaml.ansible

- name: Install exa
  become: true
  when: "not ('exa' | is_installed)"
  block:
    - name: Get latest version of exa
      get_latest_github_tag:
        owner: ogham
        repo: exa
      register: gh_tag
    - name: Create exa tmp dir
      ansible.builtin.file:
        path: /tmp/exa
        state: directory
        mode: '0755'
    - name: Extract exa archive
      ansible.builtin.unarchive:
        src: "https://github.com/ogham/exa/releases/download/{{ gh_tag.latest }}/exa-linux-x86_64-{{ gh_tag.latest }}.zip"
        dest: /tmp/exa
        remote_src: true
    - name: Install exa bin
      ansible.builtin.copy:
        src: "/tmp/exa/bin/exa"
        dest: /usr/local/bin/exa
        mode: '0755'
    - name: Install exa bash completion
      ansible.builtin.copy:
        src: "/tmp/exa/completions/exa.bash"
        dest: "{{ bash_completions_dir }}/exa"
        mode: '0644'
    - name: Install exa zsh completion
      ansible.builtin.copy:
        src: "/tmp/exa/completions/exa.zsh"
        dest: "{{ zsh_completions_dir }}/_exa"
        mode: '0644'
    - name: Install exa man page
      ansible.builtin.copy:
        src: "/tmp/exa/man/exa.1"
        dest: "{{ man_dir }}/exa.1"
        mode: '0644'
    - name: Remove exa temporary files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/exa"
