# vim: filetype=yaml.ansible

- name: Install fd
  become: true
  ansible.builtin.package:
    name:
      - "{{ fd_pkg_name }}"
    state: present

- name: Create symbolic link to fd binary if fdfind is used
  become: true
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  when:
    - ansible_distribution == "Ubuntu"
    - "'/usr/bin/fdfind' is file and '/usr/local/bin/fd' is not file"
