# vim: filetype=yaml.ansible

- name: Download and install lua language server
  vars:
    bin_dir: "~/.local/bin"
    luals_bin_path: "{{ bin_dir }}/lua-language-server"
    luals_dir_path: "{{ bin_dir }}/luals-linux64"
    tmp_tar_path: "/tmp/luals.tar.gz"
  when: "not ('lua-language-server' | is_installed)"
  block:
    - name: Get latest version of lua-ls
      get_latest_github_tag:
        owner: LuaLS
        repo: lua-language-server
      register: gh_tag
    - name: Create bin dir
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
        mode: '0755'
    - name: Download lua-ls release
      ansible.builtin.get_url:
        url: "https://github.com/LuaLS/lua-language-server/releases/download/{{ gh_tag.latest }}/lua-language-server-{{ gh_tag.latest }}-linux-x64.tar.gz"
        dest: "{{ tmp_tar_path }}"
        mode: "0755"
    - name: Create the lua-ls directory
      ansible.builtin.file:
        path: "{{ luals_dir_path }}"
        state: directory
        mode: '0755'
    - name: Extract lua-ls tar
      ansible.builtin.unarchive:
        src: "{{ tmp_tar_path }}"
        dest: "{{ luals_dir_path }}"
        copy: false
        mode: '0755'
    - name: Link lua-ls binary
      ansible.builtin.file:
        src: "{{ luals_dir_path }}/bin/lua-language-server"
        dest: "{{ luals_bin_path }}"
        state: link
        force: true
    - name: Remove temporary files
      ansible.builtin.file:
        path: "{{ tmp_tar_path }}"
        state: absent
