# vim: filetype=yaml.ansible

- name: Override some variables based on distribution
  ansible.builtin.include_vars: "{{ item }}"
  with_fileglob:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
  when: item is file

# Things that will be used for installing other packages
- name: Install core dependencies and package managers
  become: true
  ansible.builtin.package:
    name:
      - "{{ python_pkg_name }}"
      - "{{ pip_pkg_name }}"
      - nodejs
      - npm
    state: present

- name: Setup nodejs to use lts version
  become: true
  block:
    - name: Install 'n' node version manager
      community.general.npm:
        name: n # Used for installing newer node versions
        global: true
        state: present
    - name: Set node/npm versions to lts
      become: true
      ansible.builtin.shell: |
        node_ver="$(node --version)"
        node_ver="${node_ver#v}"
        lts_ver="$(sudo n --lts)"
        if [[ "${node_ver}" != "${lts_ver}" ]]; then
          sudo n lts
          echo "NODE_VER_EQ"
        fi
      args:
        executable: /bin/bash
      register: node_ver_check
      changed_when: '"NODE_VER_EQ" in node_ver_check.stdout'

# Required to use "get_latest_github" custom module
- name: Install python requests package (used for ansible config)
  become: true
  ansible.builtin.pip:
    name:
      - requests
    state: present

- name: Install all user apps
  ansible.builtin.include_tasks: "{{ outer_item }}"
  loop:
    - ansible-ls.yml
    - atool.yml
    - bat.yml
    - bitwise.yml
    - btop.yml
    - calc.yml
    - cheat.yml
    - clang-format.yml
    - clangd-ls.yml
    - cpplint.yml
    - elinks.yml
    - eza.yml
    - fd.yml
    - fzf.yml
    - jq.yml
    - json-ls.yml
    - lua-ls.yml
    - marksman-ls.yml
    - neovim.yml
    - ripgrep.yml
    - rsync.yml
    - shellcheck.yml
    - shfmt.yml
    - stylua.yml
    - tig.yml
    - tmux.yml
    - trash-cli.yml
    - tree.yml
    - unison.yml
    - wsl-open.yml
    - yaml-ls.yml
    - zellij.yml
    - zsh.yml
  loop_control:
    loop_var: outer_item
