# vim: filetype=yaml.ansible

- name: Download and install Marksman languague server
  vars:
    bin_dir: "~/.local/bin"
  when: "not ('marksman' | is_installed)"
  block:
    - name: Get latest version of marksman
      get_latest_github_tag:
        owner: artempyanykh
        repo: marksman
      register: gh_tag
    - name: Create bin dir
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
        mode: '0755'
    - name: Download & install marksman binary
      ansible.builtin.get_url:
        url: "https://github.com/artempyanykh/marksman/releases/download/{{ gh_tag.latest }}/marksman-linux-x64"
        dest: "{{ bin_dir }}/marksman"
        mode: "0755"
