# vim: filetype=yaml.ansible

- name: Download and install Neovim
  vars:
    bin_dir: "~/.local/bin"
    nvim_bin_path: "{{ bin_dir }}/nvim"
    nvim_dir_path: "{{ bin_dir }}/nvim-linux64"
    tmp_tar_path: "/tmp/nvim.tar.gz"
  when: "not ('nvim' | is_installed)"
  block:
    - name: Create bin dir
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
        mode: '0755'
    - name: Download Neovim release
      ansible.builtin.get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
        dest: "{{ tmp_tar_path }}"
        mode: "0755"
    - name: Extract Neovim tar
      ansible.builtin.unarchive:
        src: "{{ tmp_tar_path }}"
        dest: "{{ bin_dir }}"
        copy: false
        mode: '0755'
    - name: Link Neovim binary
      ansible.builtin.file:
        src: "{{ nvim_dir_path }}/bin/nvim"
        dest: "{{ nvim_bin_path }}"
        state: link
        force: true
    - name: Remove temporary files
      ansible.builtin.file:
        path: "{{ tmp_tar_path }}"
        state: absent

- name: Install neovim for nodejs
  community.general.npm:
    name: neovim
    global: true
    state: present

- name: Install neovim for python
  become: true
  ansible.builtin.pip:
    name:
      - pynvim
    state: present
