# vim: filetype=yaml.ansible

- name: Download and install stylua formatter
  vars:
    bin_dir: "~/.local/bin"
    tmp_tar_path: "/tmp/stylua.tar.gz"
  when: "not ('stylua' | is_installed)"
  block:
    - name: Get latest version of stylua
      get_latest_github_tag:
        owner: JohnnyMorganz
        repo: StyLua
      register: gh_tag
    - name: Create bin dir
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
        mode: '0755'
    - name: Download stylua release
      ansible.builtin.get_url:
        url: https://github.com/JohnnyMorganz/StyLua/releases/download/{{ gh_tag.latest }}/stylua-linux-x86_64.zip
        dest: "{{ tmp_tar_path }}"
        mode: "0755"
    - name: Extract stylua zip
      ansible.builtin.unarchive:
        src: "{{ tmp_tar_path }}"
        dest: "{{ bin_dir }}"
        copy: false
        mode: '0755'
    - name: Remove temporary files
      ansible.builtin.file:
        path: "{{ tmp_tar_path }}"
        state: absent
