# vim: filetype=yaml.ansible

- name: Install latest release of zellij-org/zellij
  become: true
  when: "not ('zellij' | is_installed)"
  block:
    - name: Get latest version of zellij
      get_latest_github_tag:
        owner: zellij-org
        repo: zellij
      register: gh_tag
    - name: Create zellij tmp dir
      ansible.builtin.file:
        path: /tmp/zellij
        state: directory
        mode: '0755'
    - name: Extract zellij archive
      ansible.builtin.unarchive:
        src: >-
          https://github.com/zellij-org/zellij/releases/download/{{ gh_tag.latest }}/zellij-x86_64-unknown-linux-musl.tar.gz
        dest: /tmp/zellij
        remote_src: true
    - name: Install zellij bin
      ansible.builtin.copy:
        src: "/tmp/zellij/zellij"
        dest: /usr/local/bin/zellij
        mode: '0755'
    - name: Remove zellij temporary files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/zellij"

- name: Setup zellij shell completions
  become: true
  ansible.builtin.shell: |
    if [ ! -f "{{ packages_bash_comp_dir }}/zellij" ] || [ ! -f "{{ packages_zsh_comp_dir }}/_zellij" ]; then
      /usr/local/bin/zellij setup --generate-completion bash > {{ packages_bash_comp_dir }}/zellij
      /usr/local/bin/zellij setup --generate-completion zsh > {{ packages_zsh_comp_dir }}/_zellij
      return 0
    fi
    return 1
  ignore_errors: true
  register: zellij_comp_res
  changed_when: "zellij_comp_res.rc == 0"
