# vim: filetype=yaml.ansible

- name: Install delta-git
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: dandavison/delta
    tag: latest
    asset_regex: delta.*(?<!musl)\.tar\.gz
    version_command: delta --version | grep -oE '\b[0-9]+\.[0-9]+\.[0-9]+\b'
    move_rules:
      - src_regex: delta-.*/delta
        dst: "/usr/local/bin"
