# vim: filetype=yaml.ansible

- name: Install github cli
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: cli/cli
    tag: latest
    asset_regex: gh_.*\.tar\.gz
    version_command: gh --version
    move_rules:
      - src_regex: gh_.*/bin/gh
        dst: "/usr/local/bin"
      - src_regex: gh_.*/share/man/man1/.*
        dst: "/usr/local/share/man/man1"

- name: Get GitHub CLI extension list
  tags: [pkgs]
  ansible.builtin.command: gh extension list
  register: gh_extension_list
  changed_when: false
  failed_when: false

- name: Install github dash
  tags: [pkgs]
  when: '"dlvhdr/gh-dash" not in gh_extension_list.stdout'
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/gh extension install dlvhdr/gh-dash
  register: dash_install_result
  changed_when: "dash_install_result.rc == 0"
