#!/bin/bash
#
# Bootsrap program for dotfiles repo.
# Built for Ubuntu (specifically 20.04)
#

# List packages to install
APT_PKGS=(
    atool
    bat
    calc
    curl
    fd-find
    htop
    neovim
    ripgrep
    rsync
    tig
    tmux
    zsh
)
APT_GRH_PKGS=( scrot sxiv zathura )
PIP_PKGS=( pynvim trash-cli )
NPM_PKGS=( neovim )

# List additional packages to install (involve more than just a pkg manager)
# FORMAT: array [bin;link]
declare -A ADD_PKGS
ADD_PKGS[cheat]='cht.sh;https://github.com/chubin/cheat.sh'
ADD_PKGS[delta]='delta;https://github.com/dandavison/delta'
ADD_PKGS[exa]='exa;https://github.com/ogham/exa'
ADD_PKGS[nnn]='nnn;https://github.com/jarun/nnn'
ADD_PKGS[ripgrep]='rg;https://github.com/BurntSushi/ripgrep'

# Manual install functions
# --------------------------
function __install_cheat {
    if curl https://cht.sh/:cht.sh | sudo tee /usr/local/bin/cht.sh &&
        sudo chmod +x /usr/local/bin/cht.sh; then
        return 0
    fi
    return 1
}
function __install_delta {
    tmp=/tmp/delta.amd64.deb
    wget https://github.com/dandavison/delta/releases/download/0.5.1/git-delta_0.5.1_amd64.deb -O $tmp &&
        sudo apt install $tmp &&
        rm $tmp &&
        return 0
    return 1
}
function __install_exa {
    tmp=/tmp/exa-linux.zip
    wget https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip -O $tmp &&
        aunpack $tmp -X $XDG_BIN_HOME &&
        mv $XDG_BIN_HOME/exa-linux-x86_64 $XDG_BIN_HOME/exa &&
        rm $tmp &&
        return 0
    return 1
}
function __install_nnn {
    tmp=/tmp/nnn.amd64.deb
    wget https://github.com/jarun/nnn/releases/download/v3.5/nnn_3.5-1_ubuntu20.04.amd64.deb -O $tmp &&
        sudo apt install $tmp &&
        rm $tmp &&
        return 0
    return 1
}
function __install_ripgrep {
    # Workaround to install bat and ripgrep (https://github.com/sharkdp/bat/issues/938)
    sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep && return 0
    return 1
}

# Functions
# -----------
# Color codes: reset = 0, black = 30, red = 31, green = 32, yellow = 33,
#              blue = 34, magenta = 35, cyan = 36, and white = 37
# Change color: "\e[1;32m", Reset: "\e[0m"

function _is_callable {
    for cmd in "$@"; do
        command -v "$cmd" >/dev/null || return 1
    done
}
function _is_graphical { ls /usr/share/xsessions/ >/dev/null 2>&1; }
function _install_pkgs {
    mgr=${1}; shift
    pkgs=("$@")

    echo -e "\e[1;32m ::\e[0m The following $mgr packages can be automatically installed:"
    echo -e "    \e[1;33m${pkgs[@]}\e[0m"
    echo -e "  \e[1;36m ::\e[0m Proceed? [Y/n] \c"
    read ans; print

    if [[ $ans =~ ^[Yy]$ ]]; then
        case "$mgr" in
            apt)
                sudo apt-get install -y ${pkgs[@]}
                ;;
            pip)
                pip3 install ${pkgs[@]}
                ;;
            npm)
                sudo npm install -g ${pkgs[@]}
                ;;
            *)
                echo -e "\e[1;31m ::\e[0m Unknown package manager $mgr" # red
                ;;
        esac
    fi
}
function _add_pkg {
    name=${1}
    func=${2}

    echo -e "\e[1;32m ::\e[0m Do you wish to '$name' automatically? [Y/n] \c"
    read ans; print
    if [[ $ans =~ ^[Yy]$ ]]; then
        $func
    fi
}

# Runners
# ---------

install_pkg_managers()
{
    sudo apt update
    _is_callable "pip3" || sudo apt install -y python3 python3-pip
    _is_callable "npm" || sudo apt install -y nodejs npm
}

install_pkgs()
{
    # Convert arrays to newline delimited strings
    pip_pkgs=$(printf '%s\n' "${PIP_PKGS[@]}")
    npm_pkgs=$(printf '%s\n' "${NPM_PKGS[@]}")

    # Get missing packages
    apt_pkgs=( $(dpkg -C "${APT_PKGS[@]}" 2>&1 | awk -F\' '{print $2}') )
    pip_pkgs=( $(pip3 freeze | grep -Fwoi "$pip_pkgs" | uniq | grep -Fwiv -f - <(echo "$pip_pkgs")) )
    npm_pkgs=( $(sudo npm -g list | grep -Fwoi "$npm_pkgs" | uniq | grep -Fwiv -f - <(echo "$npm_pkgs")) )
    _is_graphical && grh_pkgs=( $(dpkg -C "${APT_GRH_PKGS[@]}" 2>&1 | awk -F \' '{print $2}') ) || grh_pkgs=""

    # Install pkg-mgr packages
    [ -n "$apt_pkgs" ] && _install_pkgs "apt" "${apt_pkgs[@]}"
    [ -n "$grh_pkgs" ] && _install_pkgs "apt" ${grh_pkgs[@]}
    [ -n "$pip_pkgs" ] && _install_pkgs "pip" ${pip_pkgs[@]}
    [ -n "$npm_pkgs" ] && _install_pkgs "npm" ${npm_pkgs[@]}

    # List additional, manual packages for install
    for name in "${!ADD_PKGS[@]}"; do
        IFS=";" read -r -a arr <<< "${ADD_PKGS[$name]}"
        bin=${arr[0]}
        link=${arr[1]}
        _is_callable "$bin" || {
            # If install method is defined, use it
            if type __install_$name &>/dev/null; then
                _add_pkg $name __install_$name &&
                    echo "Installed $name (\e[1;34m$link\e[0m)." ||
                    echo "Failed to install $name."
            fi
        }
    done
}

# Change the default login shell for the current user.
change_login_shell()
{
    [[ $(cat /etc/passwd | grep $USER) == *:/bin/zsh ]] && return

    echo -e "\e[1;32m ::\e[0m Changing the login shell to /bin/zsh"
    chsh $USER --shell=/bin/zsh
}

# ======
# MAIN
# ======

install_pkg_managers
install_pkgs
change_login_shell

exit 0
