#!/bin/bash
#
# Bootsrap program for dotfiles repo
#

APT_PKGS=(
    atool
    bat
    calc
    fd-find
    neovim
    nnn
    ripgrep
    rsync
    tig
    tmux
)
APT_GRH_PKG=( scrot sxiv zathura )
PIP_PKGS=( howdoi pynvim trash-cli )
NPM_PKGS=( neovim )

# FORMAT: array [bin;link]
declare -A MANUAL_PKGS
MANUAL_PKGS[bottom]='btm;https://github.com/ClementTsang/bottom'
MANUAL_PKGS[delta]='delta;https://github.com/dandavison/delta'
MANUAL_PKGS[exa]='exa;https://github.com/ogham/exa'
MANUAL_PKGS[joplin]='joplin;https://joplinapp.org/terminal/'

# Functions
# -----------
# Color codes: reset = 0, black = 30, red = 31, green = 32, yellow = 33,
#              blue = 34, magenta = 35, cyan = 36, and white = 37

function _is_callable {
    for cmd in "$@"; do
        command -v "$cmd" >/dev/null || return 1
    done
}
function _is_graphical { ls /usr/share/xsessions/ >/dev/null 2>&1; }
function _install_pkgs {
    mgr=${1}; shift
    pkgs=("$@")

    echo -e "\e[1;32m ::\e[0m The following $mgr packages can be automatically installed:"
    echo -e "    \e[1;33m${pkgs[@]}\e[0m"
    echo -e "  \e[1;36m ::\e[0m Proceed? [Y/n] \c"
    read ans; print

    if [[ $ans =~ ^[Yy]$ ]]; then
        case "$mgr" in
            apt)
                sudo apt-get install -y ${pkgs[@]}
                ;;
            pip)
                pip3 install ${pkgs[@]}
                ;;
            npm)
                sudo npm install -g ${pkgs[@]}
                ;;
            *)
                echo -e "\e[1;31m ::\e[0m Unknown package manager $mgr" # red
                ;;
        esac
    fi
}

install_pkg_managers()
{
    sudo apt update
    if ! _is_callable "pip3"; then
        sudo apt install -y python3 python3-pip
    fi
    if ! _is_callable "npm"; then
        sudo apt install -y nodejs npm
    fi
}

install_pkgs()
{
    # Convert arrays to newline delimited strings
    pip_pkgs=$(printf '%s\n' "${PIP_PKGS[@]}")
    npm_pkgs=$(printf '%s\n' "${NPM_PKGS[@]}")

    # Get missing packages
    apt_pkgs=( $(dpkg -C "${APT_PKGS[@]}" 2>&1 | awk -F\' '{print $2}') )
    pip_pkgs=( $(pip3 freeze | grep -Fwoi "$pip_pkgs" | uniq | grep -Fwiv -f - <(echo "$pip_pkgs")) )
    npm_pkgs=( $(sudo npm -g list | grep -Fwoi "$npm_pkgs" | uniq | grep -Fwiv -f - <(echo "$npm_pkgs")) )
    _is_graphical && grh_pkgs=( $(dpkg -C "${APT_GRH_PKG[@]}" 2>&1 | awk -F \' '{print $2}') ) || grh_pkgs=""

    # Install packages
    [ -n "$apt_pkgs" ] && _install_pkgs "apt" "${apt_pkgs[@]}"
    [ -n "$grh_pkgs" ] && _install_pkgs "apt" ${grh_pkgs[@]}
    [ -n "$pip_pkgs" ] && _install_pkgs "pip" ${pip_pkgs[@]}
    [ -n "$npm_pkgs" ] && _install_pkgs "npm" ${npm_pkgs[@]}

    # List manual packages for install
    echo -e "\e[1;32m ::\e[0m The following optional packages can be manually installed:"
    none=true
    for name in "${!MANUAL_PKGS[@]}"; do
        IFS=";" read -r -a arr <<< "${MANUAL_PKGS[$name]}"
        bin=${arr[0]}
        link=${arr[1]}
        _is_callable "$bin" || {
            none=false
            echo -e "    \e[1;33m$name:\e[0m \e[1;34m$link\e[0m"
        }
    done
    [ "$none" == true ] && echo -e "    \e[1;34mNone.\e[0m"
}

# Change the default login shell for the current user.
change_login_shell()
{
    [[ $(cat /etc/passwd | grep $USER) == *:/bin/zsh ]] && return

    echo -e "\e[1;32m ::\e[0m Changing the login shell to /bin/zsh"
    chsh $USER --shell=/bin/zsh
}

# ======
# MAIN
# ======

install_pkg_managers
install_pkgs
change_login_shell

exit 0
