#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed nvim; then
    if [ "${__OS_ID}" = "mac" ]; then
      uninstall_pkg neovim
    else
      _run sudo rm -rf /opt/nvim
    fi
    uninstall_npm_pkg tree-sitter-cli
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if [ "${__OS_ID}" = "mac" ]; then
    is_installed nvim || { install_pkg neovim && install_npm_pkg tree-sitter-cli; }
  else
    # shellcheck disable=SC2317
    function __neovim_install_fn() {
      _run sudo rm -rf /opt/nvim
      for d in nvim-*; do
        _run sudo mv "${d}" /opt/nvim
        break
      done
      install_npm_pkg tree-sitter-cli
    }
    install_gh_pkg 'neovim/neovim' 'latest' 'nvim --version' '__neovim_install_fn'
    unset -f __neovim_install_fn
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
