#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed bat; then
    uninstall_pkg bat
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if ! is_installed bat; then
    install_pkg bat
    if [ "${__OS_LIKE}" = "debian" ]; then
      _run sudo rm -rf /usr/local/bin/bat
      _run sudo ln -s /usr/bin/batcat /usr/local/bin/bat
    fi
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
