#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

install_gh_extenstion() {
  repo="${1}"
  if ! gh extension list | grep -q "${repo}"; then
    gh extenstion install "${repo}"
  fi
}

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed gh; then
    uninstall_pkg gh
  fi
else
  if ! is_installed gh; then
    install_pkg gh
    install_gh_extenstion "yusukebe/gh-markdown-preview"
  fi
fi
