#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

cht_install_path="${__USER_BIN_DIR}/cht.sh"

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed cht.sh; then
    remove_system_bins 'cht.sh'
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if ! is_installed cht.sh; then
    _run curl https://cht.sh/:cht.sh > /tmp/cht.sh
    _run chmod +x /tmp/cht.sh
    install_system_bins '/tmp' '/tmp/cht.sh'
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
