# vim: filetype=conf

# Base configuration
# ------------------

# Set default shell
set-option -g default-shell /bin/zsh
# Mouse support
set-option -g mouse on
# Renumber windows when one is closed
set-option -g renumber-windows on
# Remove escape time delay
set -sg escape-time 0
# Time in miliseconds between multiple commands to be considered as part
# of the same chain (with the '-r' flag
set -g repeat-time 300

# Keybindings
# -----------

# Key modes: the first is for the status line, the second for all other
# modes.  With these settings, it is possible to use Emacs navigation
# where no Vi normal mode motions are possible, but keep Vi-like
# behaviour for everything else.
set -g status-keys emacs
set -g mode-keys vi

# Bind Prefix to c-space
unbind C-b
set -g prefix C-space
bind C-space send-prefix
bind l send-keys 'C-l'

# Window navigation without prefix
bind -n S-Right next-window
bind -n S-Left previous-window

# Use PREFIX = to split window horizontally and PREFIX - to split vertically
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c '#{pane_current_path}'

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind tab last-window

# Toggle statusbar
bind C-s set-option status

# Drag to re-order windows
bind-key -n MouseDrag1Status swap-window -t=

# Double click on the window list to open a new window
bind-key -n DoubleClick1Status new-window

# reload config without killing server
bind r source-file $TMUX_HOME/tmux.conf \; display-message "  Config reloaded..".

# Plugins
# -------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'mattdavis90/base16-tmux'
set -g @continuum-boot 'on'
set -g @colors-base16 'default-dark'

# User Interface
# --------------

# Title and window settings
# NOTE auto rename is disabled for the given window upon manual rename.
set -g set-titles on # string shown on titlebars or programs such as `xwininfo`
set -g set-titles-string "#T" # title format
set -g automatic-rename on # name windows with <prefix>, (sessions with <prefix>$)
set -g aggressive-resize off # manpage says "on" is bad for shells…
set -g alternate-screen on

# Start indices from 1 for both windows and panes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Feedback (numbers represent miliseconds)
set -g display-panes-time 1200 # indicators for `display-panes` command
set -g display-time 1200 # use 0 to keep status line messages until key press

# Startup
# -------
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
# Run tpm
run '~/.config/tmux/plugins/tpm/tpm'
