# vim: filetype=conf

# General settings
# ==================

# Mouse support
set-option -g mouse on
# Start indices from 1 for both windows and panes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
# No bells at all
set-option -g bell-action none
# Set shell
set-option -g default-shell "${SHELL}"
# No delay on escape
set-option -s escape-time 0
# Set history limit
set-option -g history-limit 50000
# Focus events enabled for terminals that support them
set-option -g focus-events on
# Useful for multi-monitor setup
set-window-option -g aggressive-resize on

# Keys
# ======

# Bind Prefix
set-option -g prefix `
bind-key ` send-prefix

# Reload config
bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Emacs key bindings in tmux command prompt (prefix + :)
set-option -g status-keys emacs

# Panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-q kill-pane

# Windows
bind -n M-c new-window
bind -n M-n next-window
bind -n M-p previous-window
bind -n M-s split-window -v -c '#{pane_current_path}'
bind -n M-v split-window -h -c '#{pane_current_path}'
bind -r < swap-window -t -1 \; previous-window
bind -r > swap-window -t +1 \; next-window
bind -n M-Q kill-window

# Appearence
# ============

# Ensure colors look correct
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# Status bar
set -g status           on
set -g status-position  bottom
set -g monitor-activity off
set-window-option -g status-bg colour00
set-window-option -g status-fg colour05
set-window-option -g window-status-current-format "#[fg=black,bg=blue] #I:#W "
set-window-option -g window-status-format "#[fg=brightblack] #I:#W "
set-window-option -g status-right '#[fg=green]#H '
set-window-option -g window-status-style fg=white,bg=default
set-window-option -g message-style fg=red,bg=default

# Plugins
# =========
TPLUG="$TMUX_CACHE_DIR/plugins"
set-environment -g TMUX_PLUGIN_MANAGER_PATH $TPLUG

# Install tpm if not installed
if "test ! -d $TPLUG/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm $TPLUG/tpm && $TPLUG/tpm/bin/install_plugins'"

# Define plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b $TPLUG/tpm/tpm
