# vim: filetype=conf

# General settings
# ==================

# Mouse support
set-option -g mouse on
# Start indices from 1 for both windows and panes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
# No bells at all
set-option -g bell-action none
# Set shell
set-option -g default-shell "${SHELL}"
# No delay on escape
set-option -s escape-time 0
# Set history limit
set-option -g history-limit 50000
# Focus events enabled for terminals that support them
set-option -g focus-events on
# Useful for multi-monitor setup
set-window-option -g aggressive-resize on
# Emacs key bindings in tmux command prompt (prefix + :)
set-option -g status-keys emacs

# Keys
# ======

# Change prefix key to C-a, easier to type, same to "screen"
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Reload tmux configuration
bind C-r source-file $TMUX_CONFIG \; display "$TMUX_CONFIG reloaded"

# Panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind + resize-pane -Z # Zoom pane
bind -r J resize-pane -D 5 # [ PREFIX + H/J/K/L ] Resize pane
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind x kill-pane

# Windows
bind -r C-p previous-window
bind -r C-n next-window
bind -r a last-window # cycle thru MRU tabs
bind -r < swap-window -t -1 \; previous-window
bind -r > swap-window -t +1 \; next-window
bind X kill-window

# Sessions
bind Q confirm-before -p "kill-session #S? (y/n)" kill-session

# htop
bind-key T new-window "htop" \; set-option -w monitor-activity off

# Appearence
# ============

# Ensure colors look correct
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# Status bar
set -g status           on
set -g status-position  bottom
set -g monitor-activity off
set-window-option -g status-bg colour00
set-window-option -g status-fg colour05
set-window-option -g window-status-current-format "#[fg=black,bg=blue] #I:#W "
set-window-option -g window-status-format "#[fg=brightblack] #I:#W "
set-window-option -g status-right '#[fg=green]#H '
set-window-option -g window-status-style fg=white,bg=default
set-window-option -g message-style fg=red,bg=default

# Plugins
# =========
TPLUG="$TMUX_CACHE_DIR/plugins"
set-environment -g TMUX_PLUGIN_MANAGER_PATH $TPLUG

# Install tpm if not installed
if "test ! -d $TPLUG/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm $TPLUG/tpm && $TPLUG/tpm/bin/install_plugins'"

# Define plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this at bottom of tmux.conf)
run -b $TPLUG/tpm/tpm
