#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#


if [ "${UNINSTALL}" = "1" ]; then
  if is_installed lua-language-server; then
    if [ "${__OS_ID}" = "mac" ]; then
      uninstall_pkg lua-language-server
    else
      _run sudo rm -rf /opt/lua-language-server
    fi
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if [ "${__OS_ID}" = "mac" ]; then
    is_installed lua-language-server || install_pkg lua-language-server
  else
    if ! is_installed lua-language-server; then
      # shellcheck disable=SC2317
      function __luals_install_fn() {
        _run sudo rm -rf /opt/lua-language-server
        _run rm -rf ./*.tar.gz
        _run sudo mkdir -p /opt/lua-language-server
        _run sudo cp -r . /opt/lua-language-server
      }
      install_gh_pkg 'LuaLS/lua-language-server' 'latest' 'echo 0.0' '__luals_install_fn'
      unset -f __luals_install_fn
    fi
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
