# vim: filetype=yaml.ansible

- name: Install python
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - "{{ 'python' if 'arch' in ansible_distribution.lower() else 'python3' }}"
      - "{{ 'python-pip' if 'arch' in ansible_distribution.lower() else 'python3-pip' }}"
      - pipx
    state: present

- name: Install python dotfiles
  tags: [dots, python-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
