# vim: filetype=yaml.ansible

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    autoremove: true
  when: system_package_update

- name: Upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
  when: system_package_upgrade
