#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  # Zsh install on mac by default
  if [ "${__OS_ID}" != "mac" ]; then
    if is_installed zsh; then
      uninstall_pkg zsh
      chsh -s "$(which bash)" "${USER}"
    fi
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  # Zsh install on mac by default
  if [ "${__OS_ID}" != "mac" ]; then
    if ! is_installed zsh; then
      install_pkg zsh
    fi
    zsh_path="$(which zsh)"
    if [ "${SHELL}" != "${zsh_path}" ]; then
      info "Setting zsh as default shell"
      chsh -s "${zsh_path}" "${USER}"
    fi
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
