#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  # Mac already has a 'trash' bin
  if [ "${__OS_ID}" != "mac" ] ; then
    is_installed trash && uninstall_pkg trash-cli
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  # Mac already has a 'trash' bin
  if [ "${__OS_ID}" != "mac" ]; then
    is_installed trash || install_pkg trash-cli
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
