# vim: filetype=yaml.ansible

- name: Install bat
  tags: [pkgs, pkgs_cli, debug]
  when: "not ('bat' | is_installed)"
  vars:
    arch_str: >-
      {{ 'aarch64' if 'arm' in ansible_architecture or 'aarch' in ansible_architecture else 'x86_64' }}
  block:
    - name: Get latest version of bat
      get_latest_github_tag:
        owner: sharkdp
        repo: bat
      register: gh_tag
    - name: Create bat tmp dir
      ansible.builtin.file:
        path: /tmp/bat
        state: directory
        mode: '0755'
    - name: Extract bat archive
      ansible.builtin.unarchive:
        src:
          "https://github.com/sharkdp/bat/releases/download/\
           {{ gh_tag.latest }}/bat-{{ gh_tag.latest }}-{{ arch_str }}-unknown-linux-gnu.tar.gz"
        dest: /tmp/bat
        remote_src: true
        extra_opts: [--strip-components=1]
    - name: Install bat bin
      ansible.builtin.copy:
        src: "/tmp/bat/bat"
        dest: "{{ pkgs_user_bin_dir }}"
        mode: '0755'
    - name: Install bat bash completion
      ansible.builtin.copy:
        src: "/tmp/bat/autocomplete/bat.bash"
        dest: "{{ pkgs_bash_comp_dir }}/bat"
        mode: '0755'
    - name: Install bat zsh completion
      ansible.builtin.copy:
        src: "/tmp/bat/autocomplete/bat.zsh"
        dest: "{{ pkgs_zsh_comp_dir }}/_bat"
        mode: '0755'
    - name: Remove bat temporary files
      ansible.builtin.file:
        path: /tmp/bat
        state: absent
