# vim: filetype=yaml.ansible

- name: Install delta-git
  tags: [pkgs, pkgs_cli]
  when: "not ('delta' | is_installed)"
  vars:
    arch_str: >-
      {{ 'aarch64' if 'arm' in ansible_architecture or 'aarch' in ansible_architecture else 'x86_64' }}
  block:
    - name: Get latest version of delta
      get_latest_github_tag:
        owner: dandavison
        repo: delta
      register: gh_tag
    - name: Create delta tmp dir
      ansible.builtin.file:
        path: /tmp/delta
        state: directory
        mode: '0755'
    - name: Extract delta archive
      ansible.builtin.unarchive:
        src:
          "https://github.com/dandavison/delta/releases/download/\
           {{ gh_tag.latest }}/delta-{{ gh_tag.latest }}-{{ arch_str }}-unknown-linux-gnu.tar.gz"
        dest: /tmp/delta
        remote_src: true
        extra_opts: [--strip-components=1]
    - name: Install delta bin
      ansible.builtin.copy:
        src: "/tmp/delta/delta"
        dest: "{{ pkgs_user_bin_dir }}"
        mode: '0755'
    - name: Remove delta temporary files
      ansible.builtin.file:
        path: /tmp/delta
        state: absent
