# vim: filetype=yaml.ansible

# - name: Install lazygit
#   tags: [pkgs, pkgs_cli]
#   when: "not ('lazygit' | is_installed)"
#   vars:
#     arch_str: >-
#       {{ 'arm64' if 'arm' in ansible_architecture or 'aarch' in ansible_architecture else 'x86_64' }}
#   block:
#     - name: Get latest version of lazygit
#       get_latest_github_tag:
#         owner: jesseduffield
#         repo: lazygit
#       register: gh_tag
#     - name: Create lazygit tmp dir
#       ansible.builtin.file:
#         path: /tmp/lazygit
#         state: directory
#         mode: '0755'
#     - name: Extract lazygit archive
#       ansible.builtin.unarchive:
#         src:
#           "https://github.com/jesseduffield/lazygit/releases/download/\
#            {{ gh_tag.latest }}/lazygit_{{ gh_tag.latest | regex_replace('^v', '') }}_Linux_{{ arch_str }}.tar.gz"
#         dest: /tmp/lazygit
#         remote_src: true
#     - name: Install lazygit bin
#       ansible.builtin.copy:
#         src: "/tmp/lazygit/lazygit"
#         dest: "{{ pkgs_user_bin_dir }}"
#         mode: '0755'
#     - name: Remove lazygit temporary files
#       ansible.builtin.file:
#         path: /tmp/lazygit
#         state: absent
