# vim: filetype=yaml.ansible

# - name: Download and install lua language server
#   tags: [pkgs, pkgs_cli, pkgs_lsp]
#   vars:
#     arch_str: >-
#       {{ 'arm64' if 'arm' in ansible_architecture or 'aarch' in ansible_architecture else 'x64' }}
#   when: "not ('lua-language-server' | is_installed)"
#   block:
#     - name: Get latest version of lua-ls
#       get_latest_github_tag:
#         owner: LuaLS
#         repo: lua-language-server
#       register: gh_tag
#     - name: Create lua-ls dir
#       ansible.builtin.file:
#         path: "{{ pkgs_user_bin_dir }}/lua-ls"
#         state: directory
#         mode: '0755'
#     - name: Extract lua-ls archive
#       ansible.builtin.unarchive:
#         src: >
#           https://github.com/LuaLS/lua-language-server/releases/download/{{ gh_tag.latest }}/lua-language-server-{{ gh_tag.latest }}-linux-{{ arch_str }}.tar.gz
#         dest: "{{ pkgs_user_bin_dir }}/lua-ls"
#         remote_src: true
#     - name: Link lua-ls binary
#       ansible.builtin.file:
#         src: "{{ pkgs_user_bin_dir }}/lua-ls/bin/lua-language-server"
#         dest: "{{ pkgs_user_bin_dir }}/lua-language-server"
#         state: link
#         force: true
