# vim: filetype=yaml.ansible

- name: Download and install Neovim using bob
  tags: [pkgs, pkgs_cli]
  vars:
    arch_str: >-
      {{ 'aarch64' if 'arm' in ansible_architecture or 'aarch' in ansible_architecture else 'x86_64' }}
  when: not ('bob' | is_installed) or not ('nvim' | is_installed)
  block:
    - name: Get latest version of nvim-bob
      get_latest_github_tag:
        owner: MordechaiHadad
        repo: bob
      register: gh_tag
    - name: Create nvim-bob tmp dir
      ansible.builtin.file:
        path: /tmp/bob
        state: directory
        mode: '0755'
    - name: Extract nvim-bob archive
      ansible.builtin.unarchive:
        src: >
          https://github.com/MordechaiHadad/bob/releases/download/{{ gh_tag.latest }}/bob-linux-{{ arch_str }}.zip
        dest: /tmp/bob
        remote_src: true
    - name: Install nvim-bob bin
      ansible.builtin.copy:
        src: /tmp/bob/bob-linux-{{ arch_str }}/bob
        dest: "{{ pkgs_user_bin_dir }}"
        mode: '0755'
    - name: Remove nvim-bob temporary files
      ansible.builtin.file:
        path: /tmp/bob
        state: absent
    - name: Set nvim to stable release using bob
      ansible.builtin.shell: "{{ pkgs_user_bin_dir }}/bob use stable"
      args:
        executable: /bin/bash
      register: bob_use_result
      changed_when: "bob_use_result.rc == 0"

- name: Install neovim for nodejs
  become: true
  community.general.npm:
    name: neovim
    global: true
    state: present

- name: Install neovim for python
  become: true
  ansible.builtin.pip:
    name:
      - pynvim
    state: present
