# vim: filetype=yaml.ansible

- name: Download and install stylua formatter
  tags: [pkgs, pkgs_cli]
  vars:
    arch_str: >-
      {{ 'aarch64' if 'arm' in ansible_architecture or 'aarch' in ansible_architecture else 'x86_64' }}
  when: "not ('stylua' | is_installed)"
  block:
    - name: Get latest version of stylua
      get_latest_github_tag:
        owner: JohnnyMorganz
        repo: StyLua
      register: gh_tag
    - name: Create stylua tmp dir
      ansible.builtin.file:
        path: /tmp/stylua
        state: directory
        mode: '0755'
    - name: Extract stylua archive
      ansible.builtin.unarchive:
        src: >
          https://github.com/JohnnyMorganz/StyLua/releases/download/{{ gh_tag.latest }}/stylua-linux-{{ arch_str }}.zip
        dest: /tmp/stylua
        remote_src: true
    - name: Install stylua bin
      ansible.builtin.copy:
        src: "/tmp/stylua/stylua"
        dest: "{{ pkgs_user_bin_dir }}"
        mode: '0755'
    - name: Remove stylua temporary files
      ansible.builtin.file:
        path: /tmp/stylua
        state: absent
