# vim: filetype=yaml.ansible

- name: Install win32yank only on WSL machines
  tags: [pkgs, pkgs_cli]
  when: "ansible_env.WSLENV is defined and not ('win32yank.exe' | is_installed)"
  block:
    - name: Get latest version of win32yank
      get_latest_github_tag:
        owner: equalsraf
        repo: win32yank
      register: gh_tag
    - name: Create win32yank tmp dir
      ansible.builtin.file:
        path: /tmp/win32yank
        state: directory
        mode: '0755'
    - name: Extract win32yank archive
      ansible.builtin.unarchive:
        src: >-
          https://github.com/equalsraf/win32yank/releases/download/{{ gh_tag.latest }}/win32yank-x64.zip
        dest: /tmp/win32yank
        remote_src: true
    - name: Install win32yank bin
      ansible.builtin.copy:
        src: /tmp/win32yank/win32yank.exe
        dest: "{{ pkgs_user_bin_dir }}"
        mode: '0755'
    - name: Remove win32yank temporary files
      ansible.builtin.file:
        path: /tmp/win32yank
        state: absent
