# vim: filetype=yaml.ansible

- name: Install latest release of zellij-org/zellij
  tags: [pkgs, pkgs_cli]
  become: true
  when: "not ('zellij' | is_installed)"
  block:
    - name: Get latest version of zellij
      get_latest_github_tag:
        owner: zellij-org
        repo: zellij
      register: gh_tag
    - name: Create zellij tmp dir
      ansible.builtin.file:
        path: /tmp/zellij
        state: directory
        mode: '0755'
    - name: Extract zellij archive
      ansible.builtin.unarchive:
        src: >-
          https://github.com/zellij-org/zellij/releases/download/{{ gh_tag.latest }}/zellij-x86_64-unknown-linux-musl.tar.gz
        dest: /tmp/zellij
        remote_src: true
    - name: Install zellij bin
      ansible.builtin.copy:
        src: "/tmp/zellij/zellij"
        dest: /usr/local/bin/zellij
        mode: '0755'
    - name: Remove zellij temporary files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/zellij"

- name: Create zellij bash completion file if not existing
  become: true
  ansible.builtin.shell: >-
    /usr/local/bin/zellij setup --generate-completion bash > {{ pkgs_bash_comp_dir }}/zellij
  args:
    chdir: "{{ pkgs_bash_comp_dir }}"
    creates: "{{ pkgs_bash_comp_dir }}/zellij"

- name: Create zellij zsh completion file if not existing
  become: true
  ansible.builtin.shell: >-
    /usr/local/bin/zellij setup --generate-completion zsh > {{ pkgs_zsh_comp_dir }}/_zellij
  args:
    chdir: "{{ pkgs_zsh_comp_dir }}"
    creates: "{{ pkgs_zsh_comp_dir }}/_zellij"
