#!/usr/bin/env bash

# TODO: Re-evaluate whether to use for zellij
# if test -z "${BASE16_COLOR_00_HEX}"; then
#     exit
# fi
#
# zellij_config_dir="${HOME}/.config/zellij"
# zellij_themes_dir="${zellij_config_dir}/themes" && mkdir -p "$zellij_themes_dir"
#
# cat <<EOF > "${zellij_themes_dir}/default.kdl"
# themes {
#     default {
#         text_unselected {
#             base "#${BASE16_COLOR_07_HEX}"
#             background "#${BASE16_COLOR_01_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0A_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         text_selected {
#             base "#${BASE16_COLOR_07_HEX}"
#             background "#${BASE16_COLOR_02_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0A_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         ribbon_selected {
#             base "#${BASE16_COLOR_01_HEX}"
#             background "#${BASE16_COLOR_0A_HEX}"
#             emphasis_0 "#${BASE16_COLOR_08_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0E_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0C_HEX}"
#         }
#         ribbon_unselected {
#             base "#${BASE16_COLOR_01_HEX}"
#             background "#${BASE16_COLOR_06_HEX}"
#             emphasis_0 "#${BASE16_COLOR_08_HEX}"
#             emphasis_1 "#${BASE16_COLOR_07_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0C_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         table_title {
#             base "#${BASE16_COLOR_0A_HEX}"
#             background "#${BASE16_COLOR_00_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0A_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         table_cell_selected {
#             base "#${BASE16_COLOR_07_HEX}"
#             background "#${BASE16_COLOR_02_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0A_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         table_cell_unselected {
#             base "#${BASE16_COLOR_07_HEX}"
#             background "#${BASE16_COLOR_01_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0A_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         list_selected {
#             base "#${BASE16_COLOR_07_HEX}"
#             background "#${BASE16_COLOR_02_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0A_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         list_unselected {
#             base "#${BASE16_COLOR_07_HEX}"
#             background "#${BASE16_COLOR_01_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0A_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0E_HEX}"
#         }
#         frame_selected {
#             base "#${BASE16_COLOR_0A_HEX}"
#             background "#${BASE16_COLOR_00_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0E_HEX}"
#             emphasis_3 "#${BASE16_COLOR_00_HEX}"
#         }
#         frame_highlight {
#             base "#${BASE16_COLOR_0F_HEX}"
#             background "#${BASE16_COLOR_00_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0E_HEX}"
#             emphasis_1 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0F_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0F_HEX}"
#         }
#         exit_code_success {
#             base "#${BASE16_COLOR_0A_HEX}"
#             background "#${BASE16_COLOR_00_HEX}"
#             emphasis_0 "#${BASE16_COLOR_0B_HEX}"
#             emphasis_1 "#${BASE16_COLOR_01_HEX}"
#             emphasis_2 "#${BASE16_COLOR_0E_HEX}"
#             emphasis_3 "#${BASE16_COLOR_0C_HEX}"
#         }
#         exit_code_error {
#             base "#${BASE16_COLOR_08_HEX}"
#             background "#${BASE16_COLOR_00_HEX}"
#             emphasis_0 "#${BASE16_COLOR_09_HEX}"
#             emphasis_1 "#${BASE16_COLOR_00_HEX}"
#             emphasis_2 "#${BASE16_COLOR_00_HEX}"
#             emphasis_3 "#${BASE16_COLOR_00_HEX}"
#         }
#         multiplayer_user_colors {
#             player_1 "#${BASE16_COLOR_0E_HEX}"
#             player_2 "#${BASE16_COLOR_0C_HEX}"
#             player_3 "#${BASE16_COLOR_00_HEX}"
#             player_4 "#${BASE16_COLOR_09_HEX}"
#             player_5 "#${BASE16_COLOR_0B_HEX}"
#             player_6 "#${BASE16_COLOR_00_HEX}"
#             player_7 "#${BASE16_COLOR_08_HEX}"
#             player_8 "#${BASE16_COLOR_00_HEX}"
#             player_9 "#${BASE16_COLOR_00_HEX}"
#             player_10 "#${BASE16_COLOR_00_HEX}"
#         }
#     }
# }
# EOF
# # TODO: Evaluate if to reload zellij config
# touch "${zellij_config_dir}/config.kdl"
