# vim: filetype=yaml.ansible

- name: Install git
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - git
    state: present

- name: Install git dotfiles
  tags: [dots, git-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
