#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed sesh; then
    if [ "${__OS_ID}" = "mac" ]; then
      uninstall_pkg sesh
    else
      remove_system_bins "sesh"
      remove_system_bash_completions 'sesh.bash'
      remove_system_zsh_completions '_sesh'
      remove_system_fish_completions 'sesh.fish'
      remove_system_manpages man1 'sesh*'
    fi
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if [ "${__OS_ID}" = "mac" ]; then
    is_installed sesh || install_pkg sesh
  else
    # shellcheck disable=SC2317
    function __sesh_install_fn() {
      install_system_bins '.' './sesh'
      _run mkdir -p ./comp
      _run --redirect comp/sesh sesh completion bash
      _run --redirect comp/_sesh sesh completion zsh
      _run --redirect comp/sesh.fish sesh completion fish
      install_system_bash_completions '.' './comp/sesh'
      install_system_zsh_completions '.' './comp/_sesh'
      install_system_fish_completions '.' './comp/sesh.fish'
      install_system_manpages man1 '.' './man/man1/*.1'
    }
    install_gh_pkg 'joshmedeski/sesh' 'latest' 'sesh --version' '__sesh_install_fn'
    unset -f __sesh_install_fn
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
