# vim: filetype=yaml.ansible

- name: Set ~/.stowrc contents
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.stowrc"
    content: |
      --no-folding
      --dir={{ playbook_dir }}/config
      --target={{ ansible_env.HOME }}
    mode: '0644'

- name: Clean up home
  vars:
    remove_list:
      - "{{ ansible_env.HOME }}/.lesshst"
      - "{{ ansible_env.HOME }}/.lesskey"
      - "{{ ansible_env.HOME }}/.viminfo"
      - "{{ ansible_env.HOME }}/.tig_history"
      - "{{ ansible_env.HOME }}/.calc_history"
      - "{{ ansible_env.HOME }}/.zcompdump"
    backup_list:
      - "{{ ansible_env.HOME }}/.gitignore"
      - "{{ ansible_env.HOME }}/.npmrc"
      - "{{ ansible_env.HOME }}/.ripgreprc"
      - "{{ ansible_env.HOME }}/.config/git/config"
      - "{{ ansible_env.HOME }}/.bash_logout"
      - "{{ ansible_env.HOME }}/.bashrc"
      - "{{ ansible_env.HOME }}/.zshrc"
      - "{{ ansible_env.HOME }}/.profile"
      - "{{ ansible_env.HOME }}/.p10k.zsh"
      - "{{ ansible_env.HOME }}/.tmux.conf"
  block:
    - name: Remove unwanted dotfiles
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ remove_list }}"
    - name: Get the file stat of each file to backup
      ansible.builtin.stat:
        path: "{{ item }}"
      loop: "{{ backup_list }}"
      register: file_stat
    - name: Backup duplicate dotfiles
      ansible.builtin.command: mv "{{ item.item }}" "{{ item.item }}.bak"
      with_items: "{{ file_stat.results }}"
      register: backup_results
      when: item.stat.exists and item.stat.isreg
      no_log: true
      changed_when: backup_results.results | selectattr("rc", "eq", 0) | list | length > 0

- name: Build directories list
  ansible.builtin.find:
    paths: [config]
    recurse: false
    file_type: directory
  register: dotfiles

- name: Deploy dotfiles!
  with_items: '{{ dotfiles.files }}'
  ansible.builtin.shell: |
    PKG={{ item.path | replace("config/", "") }}
    stow -R ${PKG}
  args:
    chdir: config
    executable: /bin/bash
  loop_control:
    label: |-
      {% if output.stderr | length > 1 %}
      {{ item.path }}
      {{ output.stderr }}
      {%- else %}
      {{ item.path }}
      {%- endif %}
  register: output
  changed_when: '"LINK" in output.stderr'
