#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed fd; then
    uninstall_pkg 'fd[debian=fd-find][ubuntu=fd-find]'
  fi
else
  if ! is_installed fd; then
    install_pkg 'fd[debian=fd-find][ubuntu=fd-find]'
    if [ "${__OS_LIKE}" = "debian" ]; then
      _run sudo rm -rf /usr/local/bin/fd
      _run sudo ln -s /usr/bin/fdfind /usr/local/bin/fd
    fi
  fi
fi
