# vim: filetype=yaml.ansible

- name: Install nodejs
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - nodejs
      - npm
    state: present

- name: Setup nodejs to use lts version
  become: true
  tags: [pkgs]
  block:
    - name: Install 'n' node version manager
      become: true
      community.general.npm:
        name: n # Used for installing newer node versions
        global: true
        state: present
    - name: Set node/npm versions to lts
      become: true
      ansible.builtin.shell: |
        node_ver="$(node --version)"
        node_ver="${node_ver#v}"
        lts_ver="$(sudo n --lts)"
        if [[ "${node_ver}" != "${lts_ver}" ]]; then
          sudo n lts
          echo "NODE_VER_EQ"
        fi
      args:
        executable: /bin/bash
      register: node_ver_check
      changed_when: '"NODE_VER_EQ" in node_ver_check.stdout'

- name: Install node dotfiles
  tags: [dots, node-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
