#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

python_bin_name="python3"
if [ "${__OS_ID}" = "arch" ]; then
  python_bin_name="python"
fi

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed "${python_bin_name}" pipx; then
    uninstall_pkg 'python3[arch=python]' 'python3-pip[arch=python-pip]' pipx
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if ! is_installed "${python_bin_name}" pipx; then
    install_pkg 'python3[arch=python]' 'python3-pip[arch=python-pip]' pipx
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
