#!/bin/bash
#
# Configuration file for the Binary Space Partitioning Window Manager.

# Truncate a couple of common commands that are used herein.
# Requirements:
#     - xrandr
_bc() {
    bspc config "$@"
}
_check() {
    command -v "$1" > /dev/null && ! pgrep -x "$1" >/dev/null
}

# Visual options
# ==============
#
# Things to bear in mind about certain configurations:
#
# 1. single_monocle true == Does not recognise receptacles, so if you
#    have a single window and insert a receptacle, the window will
#    remain in monocle view.  Desired behaviour is to tile accordingly.
# 2. borderless_monocle true == Smart borders are bad in multi-monitor
#    setups because you cannot tell which window has focus when
#    a monocle exists on each monitor.  Single monitor is okay.
# 3. ignore_ewmh_focus true == This is very opinionated as it completely
#    prevents focus stealing.  Adapt accordingly.
# 4. pointer_modifier mod1 == enables mouse actions while holding down
#    the Alt key (see below---bonus: the following two also work in the
#    popular desktop environments).
# 5. pointer_action1 move == Alt + Right Click allows you to drag
#    a floating window.  Also works for switching the position of tiled
#    windows, if that is your thing.
# 6. pointer_action2 resize_side == Alt + Left Click allows you to
#    resize the nearest side of the focused window.  Works for both
#    tiled and floating windows.
# 7. external_rules_command bspwm_external_rules == References the
#    script of mine that implements window rules and some custom
#    behaviours.  The script is also part of my dotfiles.  Window rules
#    can be included herein, but I prefer to keep them separate.
# 8. Colours are edited programmatically by my `tempus` script.  Do not
#    edit them manually (edit the script instead).  These colours
#    concern the following:
#
#    * normal_border_color   == unfocused windows
#    * active_border_color   == focused window, unfocused monitor
#    * focused_border_color  == focused window, focused monitor
#    * presel_feedback_color == area for a manual split (preselection)

# window management
# -----------------
monitors=$(xrandr | grep " connected " | awk '{ print$1 }')
primary_monitor=$(echo -e "$monitors" | awk 'NR==1 {print; exit}')
secondary_monitor=$(echo -e "$monitors" | awk 'NR==2 {print; exit}')
[ -z "$primary_monitor" ] || bspc monitor "$primary_monitor" -d 1 2 3 4
[ -z "$secondary_monitor" ] || bspc monitor "$secondary_monitor" -d 1 2

_bc border_width 1
_bc window_gap 10
_bc split_ratio 0.50
_bc single_monocle false
_bc borderless_monocle true
_bc gapless_monocle false
_bc paddingless_monocle false
_bc focus_follows_pointer false
_bc pointer_follows_monitor true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc click_to_focus any
_bc swallow_first_click false
_bc initial_polarity first_child
_bc ignore_ewmh_focus true

# window rules
# ------------
# _check bspwm_external_rules && _bc external_rules_command "$(command -v bspwm_external_rules)"
# clear rules
bspc rule -r $(bspc rule --list)
bspc rule -a scratchpad monitor="$primary_monitor" state=floating center=on rectangle=1500x800+0+0
bspc rule -a cheatsheet monitor="$primary_monitor" state=floating center=on rectangle=1500x800+0+0

# colours
# -------
_bc normal_border_color "#312e30"
_bc active_border_color "#b1942b"
_bc focused_border_color "#6da280"
_bc presel_feedback_color "#2a2829"

# autostart
# =========

# Set mouse pointer
xsetroot -cursor_name left_ptr

# Gnome-flashback is specifically designed to recover some functionality
# already moved to mutter or gnome-shell. So, it comes with some features
# built in but easy to disable if you want to.
_check gnome-flashback && gnome-flashback &

# The hotkey daemon that handles all custom key bindings, including the
# ones that control BSPWM.  No real need to check for the presence of
# this executable, because it is a dependency of the BSPWM package.
_check sxhkd && sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc{,_bspc} &

# Display compositor for enabling shadow effects and transparency
# (disable it if performance is bad---also bear in mind that I do not
# use transparent areas in any of my interfaces).
_check compton && compton --config "$HOME"/.config/compton/compton.conf &

# Launch polybar
_check polybar && polybar --reload top &

# Set keyboard layout
setxkbmap -layout 'us'
setxkbmap -option compose:menu
