# Configuration for Tinty
# https://github.com/tinted-theming/tinty
#
# This file is optional, but there is limited tinty functionality
# without customization of this config.toml
#
# This file should contain a `[[items]]` section for each application
# you want themed. You can also set a `shell` value which is used in
# Tinty when running shell commands. `shell` is also used when executing
# `hook`s provided in this config file Check tinty repository for more
# information and examples.


# Explanation and default values for keys:

# Through which shell command hooks will run. The command will be replaced in '{}'
shell = "sh -c '{}'"
# Default scheme to apply if a previously set scheme doesn't exist.
# Used specifically in the `tinty init` subcommand.
default-scheme = "base16-kanagawa"

[[items]]
# Path to template repository. Can be a URL, absolute path or path
# beginning with `~/`.
path = "https://github.com/tinted-theming/tinted-shell"
# Unique name of item
name = "tinted-shell"
# Name of the repository directory containing the theme files
themes-dir = "scripts"
# (Optional) Command to execute after copying template (goes through `shell`)
hook = ""
# (Optional) supported scheme system of template. Some templates
# could support multiple scheme systems.
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
themes-dir = "colors"
hook = "test -n \"$TMUX\" && tmux source-file %f"

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "tinted-fzf"
themes-dir = "sh"
hook = ". %f"
