# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.1"
"rocks-git.nvim" = "2.0.1"
"rocks-config.nvim" = "2.1.5"
"guess-indent.nvim" = "scm"
"lualine.nvim" = "scm"
"oil.nvim" = "2.11.0"
neogen = "2.19.0"
tree-sitter-cpp = "0.0.3"
tree-sitter-perl = "0.0.3"
tree-sitter-toml = "0.0.2"
nvim-ts-autotag = "scm"
tree-sitter-yaml = "0.0.2"
tree-sitter-tmux = "0.0.2"
"telescope.nvim" = "scm"
nvim-autopairs = "scm"
"fidget.nvim" = "1.4.1"
nvim-surround = "2.1.5"
tree-sitter-make = "0.0.2"
nvim-various-textobjs = "scm"
nvim-treesitter-context = "scm"
"which-key.nvim" = "3.13.2"
tree-sitter-cmake = "0.0.2"
tree-sitter-git_rebase = "0.0.3"
"telescope-ui-select.nvim"= "scm"
tree-sitter-diff = "0.0.2"
tree-sitter-starlark = "0.0.2"
tree-sitter-gitcommit = "0.0.2"
tree-sitter-proto = "0.0.2"
tree-sitter-git_config = "0.0.2"
"ts-comments.nvim" = "1.5.0"
nvim-snippets = "scm"
"tmux.nvim" = "scm"
friendly-snippets = "scm"
tree-sitter-json = "0.0.2"
tree-sitter-ssh_config = "0.0.2"
"obsidian.nvim" = "3.9.0"
"lspkind.nvim" = "scm"
tree-sitter-properties = "0.0.2"
"rocks-treesitter.nvim" = "1.0.2"
"schemastore.nvim" = "0.2.0"
"telescope-zf-native.nvim" = "1.0.0"
tree-sitter-python = "0.0.2"
tree-sitter-bash = "0.0.2"
"mini.diff" = "0.13.0"
"mini.bufremove" = "0.9.0"
"mini.indentscope" = "0.9.0"
nvim-cmp = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-nvim-lsp = "scm"
cmp-cmdline = "scm"
"markdown.nvim" = "5.0.0"

[plugins.base16-nvim]
version = "scm"
opt = true

[config]
plugins_dir = "plugins/"
auto_setup = false
load_opt_plugins = true

[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-buffer",
  "cmp-path",
  "cmp-nvim-lsp",
  "cmp-cmdline",
  "friendly-snippets",
  "lspkind.nvim",
  "nvim-snippets"
]

[bundles.telescope]
items = [
  "telescope-zf-native.nvim",
  "telescope-ui-select.nvim",
  "telescope.nvim"
]
