# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.2"
"rocks-git.nvim" = "2.3.1"
"rocks-config.nvim" = "3.0.0"
"rocks-treesitter.nvim" = "1.1.3"
"rocks-edit.nvim" = "scm"
"guess-indent.nvim" = "scm"
"lualine.nvim" = "scm"
"oil.nvim" = "2.12.2"
neogen = "2.19.4"
tree-sitter-cpp = "0.0.26"
tree-sitter-perl = "0.0.28"
tree-sitter-toml = "0.0.24"
nvim-ts-autotag = "scm"
tree-sitter-yaml = "0.0.24"
tree-sitter-tmux = "0.0.24"
nvim-autopairs = "scm"
"fidget.nvim" = "1.4.1"
nvim-surround = "2.1.5"
tree-sitter-make = "0.0.24"
nvim-various-textobjs = "scm"
nvim-treesitter-context = "scm"
"which-key.nvim" = "3.13.3"
tree-sitter-cmake = "0.0.24"
tree-sitter-git_rebase = "0.0.24"
tree-sitter-diff = "0.0.24"
tree-sitter-gitcommit = "0.0.24"
tree-sitter-proto = "0.0.24"
tree-sitter-git_config = "0.0.24"
"ts-comments.nvim" = "1.5.0"
nvim-snippets = "scm"
friendly-snippets = "scm"
tree-sitter-json = "scm"
tree-sitter-ssh_config = "scm"
"obsidian.nvim" = "3.9.0"
"lspkind.nvim" = "scm"
tree-sitter-properties = "scm"
"schemastore.nvim" = "0.2.0"
tree-sitter-python = "0.0.24"
tree-sitter-bash = "0.0.24"
nvim-cmp = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-nvim-lsp = "scm"
cmp-cmdline = "scm"
tree-sitter-csv = "0.0.24"
"indent-blankline.nvim" = "3.7.2"
"bufdelete.nvim" = "scm"
"render-markdown.nvim" = "7.2.0"
tree-sitter-html = "scm"
"telescope.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
"telescope-ui-select.nvim" = "scm"
"gitsigns.nvim" = "0.9.0"
tree-sitter-kconfig = "0.0.24"
tree-sitter-groovy = "0.0.24"
tree-sitter-kdl = "0.0.24"
tree-sitter-robot = "0.0.24"
base16-nvim = "scm"

[config]
plugins_dir = "plugins/"
auto_setup = false
load_opt_plugins = true

[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-buffer",
  "cmp-path",
  "cmp-nvim-lsp",
  "cmp-cmdline",
  "friendly-snippets",
  "lspkind.nvim",
  "nvim-snippets"
]

[bundles.telescope]
items = [
  "telescope.nvim",
  "telescope-zf-native.nvim",
  "telescope-ui-select.nvim"
]
