# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.0"
"rocks-git.nvim" = "2.0.1"
"rocks-config.nvim" = "2.1.4"
"guess-indent.nvim" = "scm"
"lualine.nvim" = "scm"
"oil.nvim" = "2.11.0"
neogen = "2.17.1"
tree-sitter-cpp = "0.0.3"
tree-sitter-perl = "0.0.2"
tree-sitter-toml = "0.0.2"
nvim-ts-autotag = "scm"
tree-sitter-yaml = "0.0.2"
tree-sitter-tmux = "0.0.2"
"telescope.nvim" = "scm"
nvim-autopairs = "scm"
"bufdelete.nvim" = "scm"
"fidget.nvim" = "1.4.1"
"indent-blankline.nvim" = "3.7.1"
nvim-surround = "2.1.5"
tree-sitter-make = "0.0.2"
nvim-various-textobjs = "scm"
nvim-treesitter-context = "scm"
"which-key.nvim" = "3.12.0"
tree-sitter-cmake = "0.0.2"
tree-sitter-git_rebase = "0.0.2"
"telescope-ui-select.nvim"= "scm"
tree-sitter-diff = "0.0.2"
tree-sitter-starlark = "0.0.2"
tree-sitter-gitcommit = "0.0.2"
tree-sitter-proto = "0.0.2"
tree-sitter-git_config = "0.0.2"
"ts-comments.nvim" = "1.4.0"
nvim-snippets = "scm"
"tmux.nvim" = "scm"
friendly-snippets = "scm"
tree-sitter-json = "0.0.2"
neogit = "scm"
tree-sitter-ssh_config = "0.0.2"
"obsidian.nvim" = "3.9.0"
"lspkind.nvim" = "scm"
tree-sitter-properties = "0.0.2"
"rocks-treesitter.nvim" = "1.0.2"
"schemastore.nvim" = "0.2.0"
"telescope-zf-native.nvim" = "1.0.0"

[plugins.base16-nvim]
version = "scm"
opt = true

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
rev = "d818fd0624205b34e14888358037fb6f5dc51234"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"
rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"
rev = "91ff86cd9c29299a64f968ebb45846c485725f23"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"
rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d"

[plugins.cmp-nvim-lsp-signature-help]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
rev = "031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7"

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"
rev = "d250c63aa13ead745e3a40f61fdd3470efde3923"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."markdown.nvim"]
git = "MeanderingProgrammer/markdown.nvim"
rev = "v4.1.0^{}"

[config]
plugins_dir = "plugins/"
auto_setup = false
load_opt_plugins = true

[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-buffer",
  "cmp-path",
  "cmp-nvim-lsp",
  "cmp-nvim-lsp-signature-help",
  "cmp-cmdline",
  "friendly-snippets",
  "lspkind.nvim",
  "nvim-snippets"
]

[bundles.telescope]
items = [
  "telescope-zf-native.nvim",
  "telescope-ui-select.nvim",
  "telescope.nvim"
]
