# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.0.0"
"rocks-treesitter.nvim" = "scm"
"conform.nvim" = "5.9.0"
"guess-indent.nvim" = "scm"
nvim-lint = "scm"
"schemastore.nvim" = "0.2.0"
nvim-lspconfig = "0.1.8"
"lualine.nvim" = "scm"
"oil.nvim" = "2.10.0"
neogen = "2.17.1"
"toggleterm.nvim" = "2.11.0"
tree-sitter-cpp = "scm"
tree-sitter-perl = "scm"
tree-sitter-toml = "scm"
nvim-ts-autotag = "scm"
tree-sitter-yaml = "scm"
tree-sitter-tmux = "scm"
"telescope.nvim" = "scm"
nvim-autopairs = "scm"
"bufdelete.nvim" = "scm"
"fidget.nvim" = "1.4.1"
"indent-blankline.nvim" = "3.6.2"
nvim-surround = "2.1.5"
tree-sitter-make = "scm"
nvim-various-textobjs = "scm"
nvim-treesitter-context = "scm"
"which-key.nvim" = "2.1.0"
tree-sitter-cmake = "scm"

[plugins."mason.nvim"]
version = "1.10.0"
opt = true

[plugins."mason-tool-installer.nvim"]
version = "scm"
opt = true

[plugins."mason-lspconfig.nvim"]
version = "1.29.0"
opt = true

[plugins.base16-nvim]
version = "scm"
opt = true

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.cmp-nvim-lsp-signature-help]
git = "hrsh7th/cmp-nvim-lsp-signature-help"

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"

[plugins.nvim-snippets]
git = "garymjr/nvim-snippets"
rev = "v1.0.0"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"

[plugins."lazydev.nvim"]
git = "folke/lazydev.nvim"
rev = "v1.6.0"

[plugins.luvit-meta]
git = "Bilal2453/luvit-meta"

[plugins."markdown.nvim"]
git = "MeanderingProgrammer/markdown.nvim"
rev = "v3.1.0^{}"

[plugins."ts-comments.nvim"]
git = "folke/ts-comments.nvim"
rev = "v1.2.0"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"
build = "make"

[plugins."telescope-ui-select.nvim"]
git = "nvim-telescope/telescope-ui-select.nvim"

[plugins."unimpaired.nvim"]
git = "tummetott/unimpaired.nvim"
rev = "v0.2.0"

[config]
plugins_dir = "plugins/"
auto_setup = false
load_opt_plugins = true

[bundles.mason]
items = [
  "mason.nvim",
  "mason-tool-installer.nvim",
  "mason-lspconfig.nvim"
]

[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-buffer",
  "cmp-path",
  "cmp-nvim-lsp",
  "cmp-nvim-lsp-signature-help",
  "cmp-cmdline",
  "friendly-snippets",
  "nvim-snippets"
]

[bundles.lsp]
items = [
  "luvit-meta",
  "lazydev.nvim",
  "schemastore.nvim",
  "nvim-lspconfig"
]

[bundles.telescope]
items = [
  "telescope-fzf-native.nvim",
  "telescope-ui-select.nvim",
  "telescope.nvim"
]
