#!/bin/bash

ERR_FILE="$HOME/.config/i3/output.txt"
TITLE="Email"

# Get list of window pids
pids=$(xdotool search --class "st")
for pid in $pids; do
    # Get name of window
    name=$(xdotool getwindowname $pid)
    if [[ $name == *"$TITLE"* ]]; then
        # Toggle scratchpad
        err=$(i3-msg '[ title="'$TITLE'" ] scratchpad show')

        if [[ $err == *"false"* ]]; then
            # If it never was in scratchpad, move it to there
            err=$(i3-msg '[ title="'$TITLE'" ] move scratchpad')
            [[ $err == *"false"* ]] && {
                echo "$err" > $ERR_FILE
                exit 1
            }
        fi
        exit 0
    fi
done

# Open email if not open
st -T "$TITLE" -e neomutt
exit 0
