#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed node npm; then
    uninstall_pkg nodejs 'npm[mac=]'
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if ! is_installed node npm; then
    install_pkg nodejs 'npm[mac=]'
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
