# Source: https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true
working_directory = "None" # Inherit from parent
import = [
  # uncomment the flavour you want below:
  # "catppuccin-latte.toml",
  # "catppuccin-frappe.toml",
  # "catppuccin-macchiato.toml",
  "catppuccin-mocha.toml",

  # Load local config
  "alacritty-local.toml",
]

[window]
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[env]
TERM = "xterm-256color"

[debug]
# render_timer = false
# persistent_logging = false
# log_level = "Debug"
# renderer = "None"
# print_events = true
# highlight_damage = false
# prefer_egl = false
