# vim: filetype=yaml.ansible

- name: Install eza
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: eza-community/eza
    tag: latest
    asset_regex: eza.*(?<!musl)\.tar\.gz
    version_command: eza --version | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+'
    move_rules:
      - src_regex: eza
        dst: "/usr/local/bin"

- name: Install eza dotfiles
  tags: [dots, eza-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
