#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  # if is_installed wezterm; then
  #   uninstall_pkg wezterm
  # fi
  if [ "${__IS_WSL}" -eq 1 ]; then
    _run rm -rf "${SCRIPT_DIR}"/dots/.config/wezterm/* "${__WSL_HOME}/.config/wezterm"
  else
    unstow_dots "${SCRIPT_DIR}/dots"
  fi
else
  # if ! is_installed wezterm; then
  #   install_pkg wezterm
  # fi
  if [ "${__IS_WSL}" -eq 1 ]; then
    _run mkdir -p "${__WSL_HOME}/.config/wezterm"
    _run cp -r "${SCRIPT_DIR}"/dots/.config/wezterm/* "${__WSL_HOME}/.config/wezterm"
  else
    stow_dots "${SCRIPT_DIR}/dots"
  fi
fi
