#!/usr/bin/env bash

if [ "${__SOURCED_COMMON_LIB}" != "1" ]; then
  # shellcheck source=/dev/null
  source "${COMMON_LIB:-${HOME}/.dotfiles/lib/common}" || return 1
fi
# shellcheck disable=SC2034
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Main
#

if [ "${UNINSTALL}" = "1" ]; then
  if is_installed zoxide; then
    if [ "${__OS_ID}" = "mac" ]; then
      uninstall_pkg zoxide
    else
      remove_system_bins "zoxide"
      remove_system_bash_completions 'zoxide.bash'
      remove_system_zsh_completions '_zoxide'
      remove_system_fish_completions 'zoxide.fish'
      remove_system_manpages man1 'zoxide*'
    fi
  fi
  unstow_dots "${SCRIPT_DIR}/dots"
else
  if [ "${__OS_ID}" = "mac" ]; then
    is_installed zoxide || install_pkg zoxide
  else
    # shellcheck disable=SC2317
    function __zoxide_install_fn() {
      install_system_bins '.' './zoxide'
      install_system_bash_completions '.' './completions/zoxide.bash'
      install_system_zsh_completions '.' './completions/_zoxide'
      install_system_fish_completions '.' './completions/zoxide.fish'
      install_system_manpages man1 '.' './man1/*.1'
    }
    # shellcheck disable=SC2317
    function __zoxide_system_filter_fn() {
      case "${__PLATFORM_SYSTEM}" in
        linux)
          if ! echo "${1}" | grep -e "linux" | grep -q -v -e "musleabihf" -e "andorid"; then
            debug "Asset '${1}' failed system filter" && return 1
          fi
          ;;
        darwin)
          if ! echo "${1}" | grep -q -e "apple" -e "darwin"; then
            debug "Asset '${1}' failed system filter" && return 1
          fi
          ;;
        *)
          return 1
          ;;
      esac
    }
    install_gh_pkg 'ajeetdsouza/zoxide' 'latest' 'zoxide --version' '__zoxide_install_fn' -s '__zoxide_system_filter_fn'
    unset -f __zoxide_install_fn __zoxide_system_filter_fn
  fi
  stow_dots "${SCRIPT_DIR}/dots"
fi
