cache = false

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "nvim"
preview_command = "bat --color=always ~/.dotfiles/install"

[[session]]
name = "windows dotfiles"
path = "/mnt/c/Users/Simi.Falaye/.dotfiles"
startup_command = "nvim"
preview_command = "bat --color=always /mnt/c/Users/Simi.Falaye/.dotfiles/install"
