[plugins]
tree-sitter-cpp = "0.0.32"
tree-sitter-perl = "0.0.35"
tree-sitter-toml = "0.0.30"
tree-sitter-yaml = "0.0.29"
tree-sitter-tmux = "0.0.29"
tree-sitter-make = "0.0.29"
tree-sitter-cmake = "0.0.31"
tree-sitter-git_rebase = "0.0.29"
tree-sitter-diff = "0.0.31"
tree-sitter-gitcommit = "0.0.33"
tree-sitter-proto = "0.0.29"
tree-sitter-git_config = "0.0.29"
tree-sitter-json = "scm"
tree-sitter-ssh_config = "scm"
tree-sitter-properties = "scm"
tree-sitter-python = "0.0.30"
tree-sitter-bash = "0.0.30"
tree-sitter-csv = "0.0.29"
tree-sitter-html = "scm"
tree-sitter-kconfig = "0.0.29"
tree-sitter-groovy = "0.0.29"
tree-sitter-kdl = "0.0.29"
tree-sitter-robot = "0.0.29"
tree-sitter-nix = "0.0.42"
tree-sitter-ini = "0.0.29"
tree-sitter-rust = "0.0.31"
tree-sitter-dockerfile = "0.0.29"
tree-sitter-xml = "0.0.32"
