import = ["rocks-treesitter.toml", "rocks-local.toml"]

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.42.2"
"rocks-git.nvim" = "2.5.1"
"rocks-config.nvim" = "3.1.0"
"rocks-treesitter.nvim" = "1.2.0"
"rocks-edit.nvim" = "scm"
"rocks-dev.nvim" = "1.7.0"
"guess-indent.nvim" = "scm"
"lualine.nvim" = "scm"
"oil.nvim" = "2.13.0"
neogen = "2.19.4"
nvim-ts-autotag = "scm"
nvim-autopairs = "scm"
"fidget.nvim" = "1.4.1"
nvim-surround = "2.1.5"
nvim-various-textobjs = "scm"
nvim-treesitter-context = "scm"
"which-key.nvim" = "3.14.1"
"ts-comments.nvim" = "1.5.0"
"obsidian.nvim" = "3.9.0"
"lspkind.nvim" = "scm"
"schemastore.nvim" = "0.2.0"
"indent-blankline.nvim" = "3.8.5"
"bufdelete.nvim" = "scm"
"render-markdown.nvim" = "7.6.0"
"telescope.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
"telescope-ui-select.nvim" = "scm"
"gitsigns.nvim" = "scm"
base16-nvim = "scm"
neogit = "scm"
nvim-lspconfig = "1.0.0"
"lazydev.nvim" = "scm"
efmls-configs-nvim = "1.8.0"
nvim-cmp = "scm"
cmp-nvim-lsp = "scm"
cmp-path = "scm"
cmp-buffer = "scm"
cmp-cmdline = "scm"
nvim-snippets = "scm"
friendly-snippets = "scm"

[config]
plugins_dir = "plugins/"
auto_setup = false
load_opt_plugins = true

[bundles.telescope]
items = [
  "telescope.nvim",
  "telescope-zf-native.nvim",
  "telescope-ui-select.nvim",
]

[bundles.cmp]
items = [
  "nvim-cmp",
  "cmp-nvim-lsp",
  "cmp-path",
  "cmp-buffer",
  "cmp-cmdline",
  "nvim-snippets",
  "friendly-snippets",
]
