# vim: filetype=yaml.ansible

- name: Install calc
  become: true
  tags: [pkgs]
  ansible.builtin.package:
    name:
      - calc
    state: present

- name: Install calc dotfiles
  tags: [dots, calc-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
