-- vim.pack.add({
--   {
--     src = "https://github.com/arborist-ts/arborist.nvim",
--     version = vim.version.range("*"),
--   },
-- })
--
-- -- Enable folds and indent
-- vim.wo.foldmethod = "expr"
-- vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"
--
-- require("arborist").setup({
--   prefer_wasm = true,
--   update_cadence = "weekly",
--   install_popular = false,
-- })
