# vim: filetype=yaml.ansible

- name: Download nvim
  tags: [pkgs]
  block:
    - name: Get nvim version
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          nvim --version | head -n 1
        executable: /bin/bash
      register: nvim_version
      changed_when: false
    - name: Get nvim package
      quera.github.install_from_github:
        repo: neovim/neovim
        tag: latest
        asset_regex: nvim-.*\.tar\.gz
        version_command: echo {{ nvim_version.stdout }}
        move_rules:
          - src_regex: .*
            dst: "/tmp/nvim"
      notify: "nvim_downloaded"

- name: Install neovim for nodejs
  tags: [pkgs]
  become: true
  community.general.npm:
    name: neovim
    global: true
    state: present

- name: Install neovim for python
  tags: [pkgs]
  become: true
  ansible.builtin.pip:
    name:
      - pynvim
    state: present

- name: Install luarocks
  tags: [pkgs]
  become: true
  ansible.builtin.package:
    name:
      - luarocks
    state: present

- name: Install neovim dotfiles
  tags: [dots, neovim-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
