# vim: filetype=yaml.ansible

- name: Install trash-cli
  tags: [pkgs]
  community.general.pipx:
    name: trash-cli
    state: present

- name: Install trash dotfiles
  tags: [dots, trash-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
