# vim: filetype=yaml.ansible

- name: Get latest release tag of a bat
  community.general.github_release:
    user: sharkdp
    repo: bat
    action: latest_release
  register: bat_latest

- name: Check if bat is installed
  ansible.builtin.command: dpkg-query -W bat
  register: bat_check_deb
  failed_when: bat_check_deb.rc > 1
  changed_when: bat_check_deb.rc == 1

- name: Check if bat is up to date
  when: bat_check_deb.rc == 0
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      bat --version | awk NR==1'{print $2}'
    executable: /bin/bash
  register: bat_check_ver
  changed_when: false

- name: Set bat version facts
  ansible.builtin.set_fact:
    bat_latest_tag: "{{ bat_latest['tag'] }}"
    bat_latest_version: "{{ bat_latest['tag'] | regex_replace('^v', '') }}"
    bat_installed_version: "{{ bat_check_ver }}"

- name: Install/Update bat
  become: true
  when: bat_check_deb.rc == 1 or bat_check_ver is not defined or bat_installed_version != bat_latest_version
  ansible.builtin.apt:
    deb: "https://github.com/sharkdp/bat/releases/download/{{ bat_latest_tag }}/\
      bat_{{ bat_latest_version }}_amd64.deb"
