# vim: filetype=yaml.ansible

- name: Install zellij
  tags: [pkgs]
  become: true
  quera.github.install_from_github:
    repo: zellij-org/zellij
    tag: latest
    asset_regex: zellij-.*\.tar\.gz
    version_command: zellij --version | grep -oE '\b[0-9]+\.[0-9]+\.[0-9]+\b'
    move_rules:
      - src_regex: zellij
        dst: "/usr/local/bin"
  notify: "zellij_installed"

- name: Install zellij dotfiles
  tags: [dots, zellij-dots]
  link_dotfiles:
    src_dir: "{{ role_path }}/dots"
